# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Mahsa Motegh
tagline:          'A Jekyll theme'
description:      'E-Mobility & Energy Transition Consultant'
url:              http://mahsamotegh.github.io
baseurl:          /

author:
  name:           'Mahsa Motegh'
  url:            https://twitter.com/mahsamotegh

paginate:         5
paginate_path: "/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mahsamotegh

plugins:
  - jekyll-paginate
  - jekyll-gist
